const express = require("express");
const router = express.Router();

const Family = [
    { name: "Alcalinos", col:"rosybrown"},
    { name: "Alcalinosterreos", col:"peru"},
    { name: "Metales De Transicion", col:"darkolivegreen"},
    { name: "Lantanicos", col:"palevioletred"},
    { name: "Actinidos", col:"tomato"},
    { name: "Otros Metales", col:"goldenrod"},
    { name: "Metaloides", col:"sandybrown"},
    { name: "Otros No Metales", col:"coral"},
    { name: "Halogenos", col:"silver"},
    { name: "Gases Nobles", col:"aqua"}
];
const elements = [
    {id: 1,name: "H", color: Family[7].col, lugar: 1},0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
    {id: 2,name: "L", color:Family[9].col,lugar:18},
    {id: 3,name: "Li",color: Family[0].col},
    {id: 4,name: "Be",color: Family[0].col},0,0,0,0,0,0,0,0,0,0,
    {id: 5,name: "B",color: Family[6].col},
    {id: 6,name: "C",color:Family[7].col},
    {id: 7,name: "N",color:Family[7].col},
    {id: 8,name: "O",color:Family[7].col},
    {id: 9,name: "F",color:Family[8].col},
    {id: 10,name: "Ne",color:Family[9].col},
    {id: 11,name: "Na",color:Family[0].col},
    {id: 12,name: "Mg",color:Family[0].col},0,0,0,0,0,0,0,0,0,0,
    {id: 13,name: "Al",color:Family[5].col},
    {id: 14,name: "Si",color:Family[6].col},
    {id: 15,name: "P",color:Family[7].col},
    {id: 16,name: "S",color:Family[7].col},
    {id: 17,name: "Cl",color:Family[8].col},
    {id: 18,name: "Ar",color:Family[9].col},
    {id: 19,name: "K",color:Family[0].col},
    {id: 20,name: "Ca",color:Family[0].col},
    {id: 21,name: "Sc",color:Family[1].col},
    {id: 22,name: "Ti",color:Family[1].col},
    {id: 23,name: "V",color:Family[1].col},
    {id: 24,name: "Cr",color:Family[1].col},
    {id: 25,name: "Mn",color:Family[1].col},
    {id: 26,name: "Fe",color:Family[1].col},
    {id: 27,name: "Co",color:Family[1].col},
    {id: 28,name: "Ni",color:Family[1].col},
    {id: 29,name: "Cu",color:Family[1].col},
    {id: 30,name: "Zn",color:Family[1].col},
    {id: 31,name: "Ga",color:Family[5].col},
    {id: 32,name: "Ge",color:Family[6].col},
    {id: 33,name: "As",color:Family[6].col},
    {id: 34,name: "Se",color:Family[7].col},
    {id: 35,name: "Br",color:Family[8].col},
    {id: 36,name: "Kr",color:Family[9].col},
    {id: 37,name: "Rb",color:Family[0].col},
    {id: 38,name: "Sr",color:Family[0].col},
    {id: 39,name: "Y",color:Family[1].col},
    {id: 40,name: "Zr",color:Family[1].col},
    {id: 41,name: "Nb",color:Family[1].col},
    {id: 42,name: "Mo",color:Family[1].col},
    {id: 43,name: "Tc",color:Family[1].col},
    {id: 44,name: "Ru",color:Family[1].col},
    {id: 45,name: "Rh",color:Family[1].col},
    {id: 46,name: "Pd",color:Family[1].col},
    {id: 47,name: "Ag",color:Family[1].col},
    {id: 48,name: "Cd",color:Family[1].col},
    {id: 49,name: "In",color:Family[5].col},
    {id: 40,name: "Sn",color:Family[5].col},
    {id: 51,name: "Sb",color:Family[6].col},
    {id: 52,name: "Te",color:Family[6].col},
    {id: 53,name: "I",color:Family[8].col},
    {id: 54,name: "Xe",color:Family[9].col},
    {id: 55,name: "Cs",color:Family[0].col},
    {id: 56,name: "Ba",color:Family[0].col},
    {id: 57,name: "La-Lu",color:Family[2].col},
    {name: "Hf",color:Family[1].col},
    {name: "Ta",color:Family[1].col},
    {name: "W",color:Family[1].col},
    {name: "Re",color:Family[1].col},
    {name: "Os",color:Family[1].col},
    {name: "Ir",color:Family[1].col},
    {name: "Pt",color:Family[1].col},
    {name: "Au",color:Family[1].col},
    {name: "Hg",color:Family[1].col},
    {name: "Tl",color:Family[5].col},
    {name: "Pb",color:Family[5].col},
    {name: "Bi",color:Family[5].col},
    {name: "Po",color:Family[6].col},
    {name: "At",color:Family[8].col},
    {name: "Rn",color:Family[9].col},
    {name: "Fr",color:Family[0].col},
    {name: "Ra",color:Family[0].col},
    {name: "Ac-Lr",color:Family[3].col},
    {name: "Rf",color:Family[1].col},
    {name: "Db",color:Family[1].col},
    {name: "Sg",color:Family[1].col},
    {name: "Bh",color:Family[1].col},
    {name: "Hs",color:Family[1].col},
    {name: "Mt",color:Family[1].col},
    {name: "Ds",color:Family[1].col},
    {name: "Rg",color:Family[1].col},
    {name: "Cn",color:Family[1].col},
    {name: "Nh",color:Family[5].col},
    {name: "Fl",color:Family[5].col},
    {name: "Mc",color:Family[5].col},
    {name: "Lv",color:Family[5].col},
    {name: "Ts",color:Family[8].col},
    {name: "Og",color:Family[9].col},

];

const g2 = [
  0,0,0,0,{name: "La",color:Family[2].col},
    {name: "Ce",color:Family[2].col},
    {name: "Pr",color:Family[2].col},
    {name: "Nd",color:Family[2].col},
    {name: "Sm",color:Family[2].col},
    {name: "Eu",color:Family[2].col},
    {name: "Gd",color:Family[2].col},
    {name: "Tb",color:Family[2].col},
    {name: "Dy",color:Family[2].col},
    {name: "Ho",color:Family[2].col},
    {name: "Er",color:Family[2].col},
    {name: "Tm",color:Family[2].col},
    {name: "Yb",color:Family[2].col},
    {name: "Lu",color:Family[2].col},0,0,0,0,
    {name: "Ac",color:Family[3].col},
    {name: "Th",color:Family[3].col},
    {name: "Pa",color:Family[3].col},
    {name: "U",color:Family[3].col},
    {name: "Np",color:Family[3].col},
    {name: "Am",color:Family[3].col},
    {name: "Cm",color:Family[3].col},
    {name: "Bk",color:Family[3].col},
    {name: "Cf",color:Family[3].col},
    {name: "Es",color:Family[3].col},
    {name: "Fm",color:Family[3].col},
    {name: "Md",color:Family[3].col},
    {name: "No",color:Family[3].col},
    {name: "Lr",color:Family[3].col},
    
]
router.get("/",function(req,res,next){
    res.render("home",{layout: false, elements, g2,Family});
});

module.exports = router;    